const iconList = [
    "404", "bug",
    "chart", "clipboard",
    "component", "dashboard",
    "documentation", "drag",
    "edit", "education",
    "email", "example",
    "excel", "exit-fullscreen",
    "eye", "eye-open",
    "form", "fullscreen",
    "guide", "notice",
    "infoCategory", "icon",
    "language", "international",
    "link", "list",
    "lock", "message",
    "money", "nested",
    "password", "pdf",
    "people", "peoples",
    "qq", "risk-list",
    "riskManagerment", "risk-measure",
    "risk-valuate", "search",
    "shopping", "standard",
    "skill", "tab",
    "star", "table",
    "theme", "tree",
    "tree-table", "user",
    "wechat", "zip"
]
export default iconList